version: "3.8"

services:
  inninglog-rest-server:
    image: 715841360397.dkr.ecr.ap-northeast-2.amazonaws.com/inninglog/rest
    container_name: inninglog-rest
    ports:
      - "8080:8080"
    env_file:
      - /home/ubuntu/.env
    environment:
      # DB 설정 - RDS 정보로 변경
      DB_URL: "${DB_URL}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"

      # JWT
      JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
      JWT_EXPIRATION: "${JWT_EXPIRATION}"

      # Kakao
      KAKAO_CLIENT_ID: "${KAKAO_CLIENT_ID}"
      KAKAO_REDIRECT_URI: "${KAKAO_REDIRECT_URI}"

      # AWS
      AWS_ACCESS_KEY: "${AWS_ACCESS_KEY}"
      AWS_SECRET_KEY: "${AWS_SECRET_KEY}"
      AWS_REGION: "${AWS_REGION}"
      AWS_S3_BUCKET: "${AWS_S3_BUCKET}"

      # Amplitude
      AMPLITUDE_API_KEY: "${AMPLITUDE_API_KEY}"