version: "3.8"

services:
  inninglog-rest-server:
    image: 715841360397.dkr.ecr.ap-northeast-2.amazonaws.com/inninglog/rest
    container_name: inninglog-rest
    ports:
      - "8080:8080"
    depends_on:
      inninglog-db:
        condition: service_healthy
      my-cache-server:
        condition: service_healthy
    env_file:
      - .env
    environment:
      # DB 설정
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_NAME: "${DB_NAME}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"

      # JWT
      JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
      JWT_EXPIRATION: "${JWT_EXPIRATION}"

      # Kakao
      KAKAO_CLIENT_ID: "${KAKAO_CLIENT_ID}"
      KAKAO_REDIRECT_URI: "${KAKAO_REDIRECT_URI}"

      # AWS
      AWS_ACCESS_KEY: "${AWS_ACCESS_KEY}"
      AWS_SECRET_KEY: "${AWS_SECRET_KEY}"
      AWS_REGION: "${AWS_REGION}"
      AWS_S3_BUCKET: "${AWS_S3_BUCKET}"

      # Amplitude
      AMPLITUDE_API_KEY: "${AMPLITUDE_API_KEY}"

  inninglog-db:
    image: mysql
    container_name: inninglog-db
    environment:
      MYSQL_ROOT_PASSWORD: pwd1234
      MYSQL_DATABASE: inningLog
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10